# Generated by Django 2.1.7 on 2021-03-16 04:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': '书籍表', 'verbose_name_plural': '书籍表'},
        ),
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='b_id',
            field=models.IntegerField(default=1615867879, max_length=20, primary_key=True, serialize=False, verbose_name='图书编号'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='b_name',
            field=models.FileField(default='book_1615867879', max_length=30, unique=True, upload_to='', verbose_name='图书名'),
        ),
        migrations.AlterModelTable(
            name='bookinfo',
            table='books_bookinfo',
        ),
    ]
