# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-30 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='编号')),
                ('author_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '作者表',
                'db_table': 'tb_authors',
                'verbose_name': '作者表',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='书籍编号')),
                ('book_name', models.CharField(max_length=20, verbose_name='书籍名称')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='books.Author', verbose_name='作者姓名')),
            ],
            options={
                'verbose_name_plural': '书籍表',
                'db_table': 'tb_books',
                'verbose_name': '书籍表',
            },
        ),
    ]
